### ISSUE TITLE
Newest Trailblazer version is not supported

### ISSUE THREAD

**Issue by TarasBardiuk** [trailblazer/trailblazer-compat#6]
Hi, guys.

The newest trailblazer-related gems look to be not supported by `trailblazer-compat`.

```
Gemfile.lock

trailblazer (2.1.0)
  trailblazer-macro (>= 2.1.0, < 2.2.0)
  trailblazer-macro-contract (>= 2.1.0, < 2.2.0)
  trailblazer-operation
trailblazer-activity (0.10.0)
  trailblazer-context (>= 0.2.0, < 0.3.0)
trailblazer-activity-dsl-linear (0.2.1)
  trailblazer-activity (>= 0.9.1, < 1.0.0)
trailblazer-cells (0.0.3)
  cells (>= 4.1.0.rc1, < 5.0.0)
trailblazer-compat (0.1.3)
  trailblazer (~> 2.0)
  uber (~> 0.0.15)
trailblazer-context (0.2.0)
trailblazer-developer (0.0.9)
  representable
  trailblazer-activity (>= 0.10.0, < 1.0.0)
  trailblazer-activity-dsl-linear
trailblazer-loader (0.1.2)
trailblazer-macro (2.1.0)
  trailblazer-operation (>= 0.6.0)
trailblazer-macro-contract (2.1.0)
  reform (>= 2.2.0, < 3.0.0)
trailblazer-operation (0.6.0)
  trailblazer-activity (>= 0.10.0, < 1.0.0)
  trailblazer-activity-dsl-linear (>= 0.2.1, < 1.0.0)
  trailblazer-developer (>= 0.0.8)
trailblazer-rails (2.1.7)
  railties (>= 4.0.0)
  trailblazer (>= 2.1.0.beta1, < 2.2.0)
  trailblazer-loader (>= 0.1.0)
```
Produces error:
```
LoadError:
  cannot load such file -- trailblazer/operation/model
# /Users/username/.rvm/gems/ruby-2.3.1@project/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
# /Users/username/.rvm/gems/ruby-2.3.1@project/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `block in require'
# /Users/username/.rvm/gems/ruby-2.3.1@project/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:258:in `load_dependency'
# /Users/username/.rvm/gems/ruby-2.3.1@project/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
# /Users/username/.rvm/gems/ruby-2.3.1@project/gems/trailblazer-compat-0.1.3/lib/trailblazer/compat.rb:22:in `<top (required)>'
# ./config/application.rb:9:in `<top (required)>'
# ./config/environment.rb:2:in `require'
# ./config/environment.rb:2:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- trailblazer-compat
#   ./config/application.rb:9:in `<top (required)>'
```

9 line in `config/application.rb` :
```
Bundler.require(*Rails.groups)
```

`trailblazer (2.0.7)` + `trailblazer-rails (1.0.11)` combination gives a following error:
```
LoadError:
  cannot load such file -- reform/rails
# /Users/username/.rvm/gems/ruby-2.3.1@project/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
# /Users/username/.rvm/gems/ruby-2.3.1@project/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `block in require'
# /Users/username/.rvm/gems/ruby-2.3.1@project/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:258:in `load_dependency'
# /Users/username/.rvm/gems/ruby-2.3.1@project/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
# /Users/username/.rvm/gems/ruby-2.3.1@project/gems/trailblazer-compat-0.1.3/lib/trailblazer/1.1/rails.rb:1:in `<top (required)>'
# /Users/username/.rvm/gems/ruby-2.3.1@project/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
# /Users/username/.rvm/gems/ruby-2.3.1@project/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `block in require'
# /Users/username/.rvm/gems/ruby-2.3.1@project/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:258:in `load_dependency'
# /Users/username/.rvm/gems/ruby-2.3.1@project/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
# /Users/username/.rvm/gems/ruby-2.3.1@project/gems/trailblazer-compat-0.1.3/lib/trailblazer/compat.rb:39:in `<top (required)>'
# ./config/application.rb:9:in `<top (required)>'
# ./config/environment.rb:2:in `require'
# ./config/environment.rb:2:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- trailblazer-compat
#   ./config/application.rb:9:in `<top (required)>'
```

So, for now, it looks like I can use `trailblazer (2.0.7)` + `trailblazer-rails (1.0.9)` combination. Still checking, but at least tests are green:)

P.S. Ruby 2.3.1 and Rails 5.1, although this is obvious)

**Comment by apotonick** [comment]
Hi Taras,

so far, we're not providing support for running 1.1 and 2.1 in the same app. Are you still maintaining 1.1 code? :open_mouth:

**Comment by TarasBardiuk** [comment]
> Are you still maintaining 1.1 code?

Yep, Nick, unfortunately:(

Okay then, I will have to use 2.0.7. But, maybe you can advise how to fix another development issue.

So, I have `trailblazer-compat (0.1.3)` + `trailblazer (2.0.7)` + `trailblazer-rails (1.0.9)` installed.
My action looks like this:
```
def verification_form
  run ::Verification::Phone::Operation::Form
  render_view :verification_form
end
```
On a first request it works, but if I change anything even not related to the trailblazer, e.g. comment out `render_view :verification_form` line, the `run` method execution above raises an exception:
```
SystemStackError: stack level too deep
from /home/username/.rvm/gems/ruby-2.3.1@project/gems/trailblazer-compat-0.1.3/lib/trailblazer/1.1/operation/controller.rb:30:in `run'
```
And it look like I can fix this only by restarting rails server. Any ideas? Huge thanks in advance:)

**Comment by spectator** [comment]
@TarasBardiuk could be related to this https://github.com/trailblazer/trailblazer-compat/pull/5 try using master instead of gem

**Comment by apotonick** [comment]
@TarasBardiuk Have you checked master of `trailblazer-compat`?

Anything blocking you from upgrading to 2.x? You can simply throw the old `#process` method into one single step?

**Comment by TarasBardiuk** [comment]
@apotonick it looks like your advice with a `master` branch helped. Thank you very much, I hope this was the last problem on the way to upgrade)

**Comment by apotonick** [comment]
I'd love to see some of those older operations, to learn what keeps you from upgrading them, @TarasBardiuk !!!
